# Generated by Django 2.1.4 on 2019-04-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='extend',
            field=models.IntegerField(default=0),
        ),
    ]
