# Generated by Django 2.1.4 on 2018-12-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reportitem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuzzcase',
            name='method',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fuzzcase',
            name='protocol',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fuzzcase',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fuzzcase',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fuzzcase',
            name='params',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
