# Generated by Django 2.1.4 on 2018-12-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181231_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskModule',
        ),
        migrations.AddField(
            model_name='taskmodule',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Task'),
            preserve_default=False,
        ),
    ]
