# Generated by Django 2.1.4 on 2019-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181231_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodule',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
