# Generated by Django 2.1.4 on 2019-01-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
