# Generated by Django 2.1.4 on 2019-08-10 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_steps_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCommonCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('sort', models.IntegerField(default=0)),
                ('case', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ui.Case')),
            ],
        ),
        migrations.CreateModel(
            name='CommonCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommonCaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('element_info', models.CharField(max_length=300)),
                ('find_type', models.CharField(max_length=300)),
                ('operate_type', models.CharField(max_length=100)),
                ('extend', models.CharField(max_length=100)),
                ('sort', models.IntegerField(default=0)),
                ('commonCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.CommonCase')),
            ],
        ),
    ]
