# Generated by Django 2.1.4 on 2019-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_casecommoncase_commoncase_commoncasestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
