# Generated by Django 2.1.4 on 2019-08-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_reportitem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportitem',
            name='extend',
            field=models.CharField(default='', max_length=100),
        ),
    ]
