# -*- coding=utf-8 -*-
__author__ = 'shikun'
__CreateAt__ = '2019/6/7-13:07'
from . import views
from django.urls import path
app_name = "ui"
urlpatterns = [
    path("dashBoard", views.dashBoard, name='dashBoard'),
    path("dashBoard_top100_case_time", views.dashBoard_top100_case_time, name='dashBoard_top100_case_time'),
    path("dashBoard_module_case", views.dashBoard_module_case, name='dashBoard_module_case'),
    path("dashBoard_top10_task", views.dashBoard_top10_task, name='dashBoard_top10_task'),
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('login_edit', views.login_edit, name='login_edit'),
    path('login_new', views.login_new, name='login_new'),
    path('login_del', views.login_del, name='login_del'),
    path('report_del', views.report_del, name='report_del'),
    path('download_log', views.download_log, name='download_log'),
    path('download_excel', views.download_excel, name='download_excel'),
    path('<int:id>/report_detail/', views.report_detail, name='report_detail'),
    path('module', views.module, name='module'),
    path('module_new', views.module_new, name='module_new'),
    path('module_edit', views.module_edit, name='module_edit'),
    path('module_del', views.module_del, name='module_del'),
    path('<int:mid>/case/', views.case, name='case'),
    path('case_new', views.case_new, name='case_new'),
    path('case_edit', views.case_edit, name='case_edit'),
    path('case_del', views.case_del, name='case_del'),
    path('<int:mid>/<int:cid>/step/', views.step, name='step'), # 第一个id为模块id,第二个为用例id
    path('step_new', views.step_new, name='step_new'),
    path('step_edit', views.step_edit, name='step_edit'),
    path('step_del', views.step_del, name='step_del'),
    path('<int:mid>/<int:cid>/check/', views.check, name='check'),  # 第一个id为模块id,第二个为用例id
    path('check_new', views.check_new, name='check_new'),
    path('check_edit', views.check_edit, name='check_edit'),
    path('check_del', views.check_del, name='check_del'),
    path('task', views.task, name="task"),
    path('task_new', views.task_new, name="task_new"),
    path('task_edit', views.task_edit, name="task_edit"),
    path('task_del', views.task_del, name="task_del"),
    path('task_run', views.task_run, name="task_run"),
    path('task_module_new', views.task_module_new, name="task_module_new"),
    path('<int:id>/task_module/', views.task_module, name="task_module"),
    path('task_module_edit', views.task_module_edit, name="task_module_edit"),
    path('task_module_del', views.task_module_del, name="task_module_del"),
    path("setting", views.setting, name="setting"),
    path("setting_edit", views.setting_edit, name="setting_edit"),
    path("common_case", views.common_case, name="common_case"),
    path("common_case_new", views.common_case_new, name="common_case_new"),
    path("common_case_edit", views.common_case_edit, name="common_case_edit"),
    path("common_case_del", views.common_case_del, name="common_case_del"),
    path("<int:id>/common_case_step/", views.common_case_step, name="common_case_step"),
    path("common_case_step_new", views.common_case_step_new, name="common_case_step_new"),
    path("common_case_step_edit", views.common_case_step_edit, name="common_case_step_edit"),
    path("common_case_step_del", views.common_case_step_del, name="common_case_step_del"),
    path("<int:mid>/<int:cid>/case_common_case/", views.case_common_case, name="case_common_case"),
    path("case_common_case_new", views.case_common_case_new, name="case_common_case_new"),
    path("case_common_case_edit", views.case_common_case_edit, name="case_common_case_edit"),
    path("case_common_case_del", views.case_common_case_del, name="case_common_case_del")

]